# Generated by Django 5.0.6 on 2024-07-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpassenger',
            name='user',
        ),
    ]
