# Generated by Django 5.0.6 on 2024-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_remove_newpassenger_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpassenger',
            name='pcount',
        ),
        migrations.AlterField(
            model_name='newpassenger',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
