# Generated by Django 5.0.6 on 2024-07-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_orderticket_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flight',
        ),
        migrations.AddField(
            model_name='order',
            name='flights',
            field=models.ManyToManyField(to='flightapp.flightaddmodel'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flightapp.order'),
            preserve_default=False,
        ),
    ]
